
ir =
  "Maximum allowed length": "حداکثر طول مجاز "
  "Minimum required length": "حداقل طول مجاز "
  add: "افزودن"
  and: "و"
  back: "برگشت"
  cancel: "انطراف"
  changePassword: "تغییر گذرواژه"
  choosePassword: "انتخاب یک گذرواژه"
  clickAgree: "با انتخاب ثبت‌نام، شما موافق هستید با"
  configure: "پیکربندی"
  createAccount: "ایجاد یک حساب"
  currentPassword: "گذرواژه کنونی"
  dontHaveAnAccount: "حساب کاربری ندارید؟"
  email: "ایمیل"
  emailAddress: "آدرس ایمیل"
  emailResetLink: "پیوند بازنشانی ایمیل"
  forgotPassword: "گذرواژه‌تان را فراموش کرده‌اید؟"
  ifYouAlreadyHaveAnAccount: "اگر هم‌اکنون یک حساب دارید"
  newPassword: "گذرواژه جدید"
  newPasswordAgain: "گذرواژه جدید (تکرار)"
  optional: "اختيارى"
  OR: "یا"
  password: "گذرواژه"
  passwordAgain: "گذرواژه (دوباره)"
  privacyPolicy: "حریم خصوصی"
  remove: "حذف"
  resetYourPassword: "بازنشانی گذرواژه شما"
  setPassword: "تنظیم گذرواژه"
  sign: "نشان"
  signIn: "ورود"
  signin: "ورود"
  signOut: "خروج"
  signUp: "ثبت‌نام"
  signupCode: "کد ثبت‌نام"
  signUpWithYourEmailAddress: "با آدرس ایمیل‌تان ثبت‌نام کنید"
  terms: "قوانین استفاده"
  updateYourPassword: "گذرواژه‌تان را به روز کنید"
  username: "نام کاربری"
  usernameOrEmail: "نام کاربری یا ایمیل"
  with: "با"
  maxAllowedLength: "ماکزیمم طول مجاز"
  minRequiredLength: "کمترین طول مجاز"
  resendVerificationEmail: "ارسال ایمیل مجدد"
  resendVerificationEmailLink_pre: "ایمیل خود را از دست داده‌اید؟"
  resendVerificationEmailLink_link: "ارسال مجدد"
  enterPassword: "رمز عبور"
  enterNewPassword: "رمز عبور جدید"
  enterEmail: "ایمیل"
  enterUsername: "نام کاربری"
  enterUsernameOrEmail: "نام‌ کاربری یا ایمیل خود را وارد کنید"
  orUse: "یا"
  "Required Field": "را وارد کنید."


  info:
    emailSent: "ایمیل ارسال شد"
    emailVerified: "ایمیل تایید شد"
    passwordChanged: "گذرواژه تغییر کرد"
    passwordReset: "گذرواژه بازنشانی شد"

  alert:
    ok: 'Ok'
    type:
      info: 'توجه'
      error: 'خطا'
      warning: 'هشدار'

  error:
    emailRequired: "ایمیل ضروری است."
    minChar: "گذرواژه حداقل ۷ کاراکتر."
    pwdsDontMatch: "گذرواژه‌ها تطابق ندارند"
    pwOneDigit: "گذرواژه باید لااقل یک رقم داشته باشد."
    pwOneLetter: "گذرواژه یک حرف نیاز دارد."
    signInRequired: "برای انجام آن باید وارد شوید."
    signupCodeIncorrect: "کد ثبت‌نام نادرست است."
    signupCodeRequired: "کد ثبت‌نام ضروری است."
    usernameIsEmail: "نام کاربری نمی‌توان آدرس ایمیل باشد."
    usernameRequired: "نام کاربری ضروری است."


    accounts:

      "Email already exists.": "ایمیل هم‌اکنون وجود دارد."
      "Email doesn't match the criteria.": "ایمیل با ضوابط تطابق ندارد."
      "Invalid login token": "علامت ورود نامعتبر است"
      "Login forbidden": "ورود نامعتبر ایمیل /نام کاربری یا رمز عبور اشتباه است"
      "Service unknown": "سرویس ناشناس"
      "Unrecognized options for login request": "گزینه‌های نامشخص برای درخواست ورود"
      "User validation failed": "اعتبارسنجی کاربر ناموفق"
      "Username already exists.": "نام کاربری هم‌اکنون وجود دارد."
      "You are not logged in.": "شما وارد نشده‌اید."
      "You've been logged out by the server. Please log in again.": "شما توسط سرور خارج شده‌اید. لطفأ دوباره وارد شوید."
      "Your session has expired. Please log in again.": "جلسه شما منقضی شده است. لطفا دوباره وارد شوید."
      "Already verified": "هم اکنون معتبر است"
      "Invalid email or username": "نام‌کاربری یا ایمیل موجود نیست"
      "Internal server error": "خطایی از طرف ما رخ داده است"
      "undefined": "خطایی رخ داده است"
      "No matching login attempt found": "تلاش ورود مطابق یافت نشد"
      "Password is old. Please reset your password.": "گذرواژه قدیمی است. لطفأ گذرواژه‌تان را بازتنظیم کنید."
      "Incorrect password": "گذرواژه نادرست"
      "Invalid email": "ایمیل نامعتبر"
      "Must be logged in": "باید وارد شوید"
      "Need to set a username or email": "یک نام کاربری یا ایمیل باید تنظیم شود"
      "old password format": "قالب گذرواژه قدیمی"
      "Password may not be empty": "گذرواژه نمی‌تواند خالی باشد"
      "Signups forbidden": "ثبت‌نام ممنوع"
      "Token expired": "علامت رمز منقظی شده است"
      "Token has invalid email address": "علامت رمز دارای آدرس ایمیل نامعتبر است"
      "User has no password set": "کاربر گذرواژه‌ای تنظیم نکرده است"
      "User not found": "کاربر یافت نشد"
      "Verify email link expired": "پیوند تایید ایمیل منقضی شده است"
      "Verify email link is for unknown address": "پیوند تایید ایمیل برای آدرس ناشناخته است"
      "At least 1 digit, 1 lowercase and 1 uppercase": "رمز عبور حداقل یک شماره یک حرف با حروف کوچک و بزرگ باید باشد"
      "Please verify your email first. Check the email and follow the link!": "لطفا ایمیل خود را ثبت کنید.ایمیل خود را چک کنید"
      "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "ایمیل جدید ارسال شد.اگر قابل مشاهده نبود لطفا بخش اسپم رو هم چک کنید"
      "Match failed": "خطا در مطابقت"
      "Unknown error": "ارور ناشناخته"
      "Error, too many requests. Please slow down. You must wait 1 seconds before trying again.": "خطا،درخواست زیاد.لطفا چند ثانیه صبر کنید و مجددا تلاش کنید"



T9n.map "ir", ir
